### ISSUE TITLE
Fix lack of permissions

### ISSUE THREAD

**Issue by nevern02** [openmailbox/mailbot#1]
```ruby
Discordrb::Errors::NoPermission: The bot doesn't have the required permission to do this!
  /var/www/mailbot/shared/bundle/ruby/2.5.0/gems/discordrb-3.2.1/lib/discordrb/api.rb:68:in `rescue in raw_request'
  /var/www/mailbot/shared/bundle/ruby/2.5.0/gems/discordrb-3.2.1/lib/discordrb/api.rb:65:in `raw_request'
  /var/www/mailbot/shared/bundle/ruby/2.5.0/gems/discordrb-3.2.1/lib/discordrb/api.rb:92:in `request'
  /var/www/mailbot/shared/bundle/ruby/2.5.0/gems/discordrb-3.2.1/lib/discordrb/api/channel.rb:70:in `create_message'
  /var/www/mailbot/shared/bundle/ruby/2.5.0/gems/discordrb-3.2.1/lib/discordrb/bot.rb:356:in `send_message'
  /var/www/mailbot/releases/20180730204556/lib/mailbot/models/jobs/update_lurk_lists.rb:67:in `block in notify_changes'
  /var/www/mailbot/shared/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/relation/batches.rb:70:in `block (2 levels) in find_each'
  /var/www/mailbot/shared/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/relation/batches.rb:70:in `each'
  /var/www/mailbot/shared/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/relation/batches.rb:70:in `block in find_each'
  /var/www/mailbot/shared/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/relation/batches.rb:136:in `block in find_in_batches'
  /var/www/mailbot/shared/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/relation/batches.rb:238:in `block in in_batches'
  /var/www/mailbot/shared/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/relation/batches.rb:222:in `loop'
  /var/www/mailbot/shared/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/relation/batches.rb:222:in `in_batches'
  /var/www/mailbot/shared/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/relation/batches.rb:135:in `find_in_batches'
  /var/www/mailbot/shared/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/relation/batches.rb:69:in `find_each'
  /var/www/mailbot/shared/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/querying.rb:11:in `find_each'
  /var/www/mailbot/releases/20180730204556/lib/mailbot/models/jobs/update_lurk_lists.rb:59:in `notify_changes'
  /var/www/mailbot/releases/20180730204556/lib/mailbot/models/jobs/update_lurk_lists.rb:12:in `perform'
  /var/www/mailbot/releases/20180730204556/lib/mailbot/scheduler.rb:16:in `block (3 levels) in start'
  /var/www/mailbot/shared/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/relation/batches.rb:70:in `block (2 levels) in find_each'
  /var/www/mailbot/shared/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/relation/batches.rb:70:in `each'
  /var/www/mailbot/shared/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/relation/batches.rb:70:in `block in find_each'
  /var/www/mailbot/shared/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/relation/batches.rb:136:in `block in find_in_batches'
  /var/www/mailbot/shared/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/relation/batches.rb:238:in `block in in_batches'
  /var/www/mailbot/shared/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/relation/batches.rb:222:in `loop'
  /var/www/mailbot/shared/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/relation/batches.rb:222:in `in_batches'
  /var/www/mailbot/shared/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/relation/batches.rb:135:in `find_in_batches'
  /var/www/mailbot/shared/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/relation/batches.rb:69:in `find_each'
  /var/www/mailbot/shared/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/querying.rb:11:in `find_each'
  /var/www/mailbot/releases/20180730204556/lib/mailbot/scheduler.rb:12:in `block (2 levels) in start'
  /var/www/mailbot/releases/20180730204556/lib/mailbot/scheduler.rb:9:in `loop'
  /var/www/mailbot/releases/20180730204556/lib/mailbot/scheduler.rb:9:in `block in start'
```

**Comment by nevern02** [comment]
https://github.com/openmailbox/mailbot/pull/2
